# Site settings
title: Runozo
email: runozo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My blog pages, mainly related to exercise me in writing in English ;-)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://runozo.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  runozo

# Build settings
markdown: kramdown
paginate: 5

# Social
og_image: favicon.ico # Default image for Open Graph tag
og_image_type: image/png
og_image_width: 16 # 300
og_image_height: 16 # 300
fb_profile_id: runozo.github.io
fb_admins: 542154016
