# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Runozo's github pages
email: cesare.ghirelli@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Runozo's github pages - A blog about python, web and data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://runozo.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  runozo

# Build settings
markdown: kramdown
