# Site settings
title: Runozo - The nerdy pages
email: runozo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My blog pages, mainly related to programming in Python and exercising me in writing in English.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://runozo.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  runozo

# Build settings
markdown: kramdown
